# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "EstimaTrack Delivery Rules"
handle = "estimatrack-delivery-rules"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback",
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "delivery-estimator"
handle = "delivery-estimator"

[extensions.metafields]

[application_url]
url = "https://localhost:3000"