# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21da9835ea07876101b969795c689201"
name = "EZ estimated delivery - Klay"
handle = "ez-estimated-delivery-klay"
application_url = "https://extra-attending-efforts-realtor.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_app_proxy"

[auth]
redirect_urls = ["https://extra-attending-efforts-realtor.trycloudflare.com/auth/callback", "https://extra-attending-efforts-realtor.trycloudflare.com/auth/shopify/callback", "https://extra-attending-efforts-realtor.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://extra-attending-efforts-realtor.trycloudflare.com/app/delivery-estimate"
subpath = "estimate"
prefix = "apps"

[pos]
embedded = false
